Fixed bridge function

diff --git a/vmrun b/vmrun
--- a/vmrun
+++ b/vmrun
@@ -7,6 +7,8 @@ DEFAULT_HOSTPORT="8022"
 DEFAULT_VMPORT="22"
 DEFAULT_VM_DIR="./vm/"
 DEFAULT_BRIDGE_NAME="br0"
+DEFAULT_INTERFACE="eth1"
+DEFAULT_TAP="tap0"
 
 VM_NAME="${PROJECT_NAME:-${DEFAULT_PROJECT_NAME}}_vm"
 PID_FILE="/tmp/${VM_NAME}.pid"
@@ -30,6 +32,8 @@ load_config() {
         VMPORT=${config_vmport:-$VMPORT}
         VM_DIR=${config_vm_dir:-$VM_DIR}
         BRIDGE_NAME=${config_bridge_name:-$BRIDGE_NAME}
+        INTERFACE=${config_interface:-$INTERFACE}
+        TAP=${config_tap:-$TAP}
     else
         echo "Config file not found: $config_file"
     fi
@@ -72,6 +76,8 @@ while [[ "$#" -gt 1 ]]; do
         --vm-port) VMPORT="$2"; shift 2;;
         --vm-dir) VM_DIR="$2"; shift 2;;
         --bridge-name) BRIDGE_NAME="$2"; shift 2;;
+        --interface) INTERFACE="$2"; shift 2;;
+        --tap) TAP="$2"; shift 2;;
         #*) echo "Unknown parameter: $1"; exit 1;;
     esac
 done
@@ -84,6 +90,9 @@ HOSTPORT=${HOSTPORT:-$DEFAULT_HOSTPORT}
 VMPORT=${VMPORT:-$DEFAULT_VMPORT}
 VM_DIR=${VM_DIR:-$DEFAULT_VM_DIR}
 BRIDGE_NAME=${BRIDGE_NAME:-$DEFAULT_BRIDGE_NAME}
+INTERFACE=${INTERFACE:-$DEFAULT_INTERFACE}
+TAP=${TAP:-$DEFAULT_TAP}
+
 
 # String var for additional disks to add if they are present
 ADD_DISKS=""
@@ -108,6 +117,7 @@ generate_additional_disks() {
 }
 generate_additional_disks
 
+
 QEMU_CMD="qemu-system-x86_64 \
   -monitor unix:${SOCKET},server,nowait \
   -display none \
@@ -119,46 +129,66 @@ QEMU_CMD="qemu-system-x86_64 \
   $ADD_DISKS
   -device e1000,netdev=net0 \
   -netdev user,id=net0,hostfwd=tcp::${HOSTPORT}-:${VMPORT}\
+  -device e1000,netdev=net1 \
+  -netdev tap,id=net1,ifname=$TAP,script=no,downscript=no  \
   -cdrom ./cloud-init/cloud-init.iso"
 
 start_vm() {
-    echo "$QEMU_CMD"
-    #check_bridge  
+    # Check if the PID file exists
     if [ -f "$PID_FILE" ]; then
-        echo "VM is already running with PID $(cat "$PID_FILE")."
-    else
-        echo "Starting VM..."
-        $QEMU_CMD > /dev/null 2>&1 &
-        QEMU_PID=$!
-        echo "Waiting VM to start..."
-        sleep 2
-        #wait $QEMU_PID
-        if [ ! -S "$SOCKET" ]; then
-            echo ""
-            echo "Could not start VM"
-            echo "$QEMU_CMD"
-            exit 1
+        VM_PID=$(cat "$PID_FILE")
+        # Check if the process is actually running
+        if ps -p "$VM_PID" > /dev/null 2>&1; then
+            echo "VM is already running with PID $VM_PID."
+            return 0 
+        else
+            echo "Stale PID file found. VM is not running, but PID file exists."
+            echo "Cleaning up stale PID file and socket."
+            rm -f "$PID_FILE" "$SOCKET" 
         fi
-        echo $! > "$PID_FILE"
-        echo "VM started with PID $(cat "$PID_FILE")."
     fi
+    check_bridge  
+    echo "Starting VM..."
+    $QEMU_CMD > /dev/null 2>&1 &
+    QEMU_PID=$!
+    echo "Waiting VM to start..."
+    sleep 2
+    #wait $QEMU_PID
+    if [ ! -S "$SOCKET" ]; then
+        echo "Failed start VM"
+        echo "$QEMU_CMD"
+        exit 1
+    fi
+    echo $! > "$PID_FILE"
+    echo "VM started with PID $(cat "$PID_FILE")."
+
 }
 
 stop_vm() {
     if [ -f "$PID_FILE" ]; then
-        echo "Stopping VM..."
+        VM_PID=$(cat "$PID_FILE")
+        echo "Stopping VM (PID: $VM_PID)..."
         echo "system_powerdown" | socat - UNIX-CONNECT:${SOCKET}
+        echo -n "Waiting for VM to shut down..."
+        while kill -0 "$VM_PID" > /dev/null 2>&1; do
+            echo -n "."
+            sleep 1
+        done
+        echo""
+        echo "VM has shutdown."
         rm -f "$PID_FILE" "$SOCKET"
-        echo "VM stopped."
+        echo "PID file and socket removed"
     else
         echo "VM is not running."
     fi
 }
 
 check_bridge() {
+    # Check if bridge already exists
     if ip link show "$BRIDGE_NAME" &> /dev/null; then
         echo "Bridge $BRIDGE_NAME exists."
     else
+        # Create the bridge if it doesn't exist
         echo "Creating bridge $BRIDGE_NAME..."
         ip link add name "$BRIDGE_NAME" type bridge
         if [ $? -ne 0 ]; then 
@@ -168,6 +198,22 @@ check_bridge() {
         ip link set dev "$BRIDGE_NAME" up
         echo "Bridge $BRIDGE_NAME created."
     fi
+    
+    # Check if physical interface is part of the bridge
+    if ! ip link show master "$BRIDGE_NAME" | grep -q "$INTERFACE"; then
+        echo "Adding interface $INTERFACE to bridge $BRIDGE_NAME..."
+        ip link set "$INTERFACE" master "$BRIDGE_NAME"
+        if [ $? -ne 0 ]; then 
+            echo "Failed to add $INTERFACE to bridge $BRIDGE_NAME."
+            exit 1
+        fi
+    else
+        echo "Interface $INTERFACE is already part of the bridge $BRIDGE_NAME."
+    fi
+    ip tuntap add dev $TAP mode tap
+    ip link set $TAP master "$BRIDGE_NAME" 
+    ip link set up dev $TAP
+    dhclient "$BRIDGE_NAME"
 }
 
 get_status() {
